-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;


-- Q2. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as (
    select customer_id, previous_purchases,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


-- Q3. What percentage of total revenue comes from the top 20% of customers by spend?
with ranked_customers as (
    select customer_id,
           purchase_amount,
           ntile(5) over (order by purchase_amount desc) as spend_quintile
    from customer
),
totals as (
    select sum(purchase_amount) as grand_total from customer
)
select spend_quintile,
       count(*) as customers_in_tier,
       round(sum(purchase_amount), 2) as tier_revenue,
       round(100.0 * sum(purchase_amount) / max(t.grand_total), 2) as pct_of_total_revenue
from ranked_customers rc
cross join totals t
group by spend_quintile, t.grand_total
order by spend_quintile;


-- Q4. What percentage of total revenue does each age group contribute?
with age_revenue as (
    select age_group, sum(purchase_amount) as total_revenue
    from customer
    group by age_group
),
grand_total as (
    select sum(purchase_amount) as overall_total from customer
)
select age_group, total_revenue,
       round(100.0 * total_revenue / (select overall_total from grand_total), 2) as pct_of_revenue
from age_revenue
order by pct_of_revenue desc;


-- Q5. Which locations generate the highest revenue per customer,
-- not just the highest total revenue?
select location,
       count(distinct customer_id) as num_customers,
       round(sum(purchase_amount), 2) as total_revenue,
       round(sum(purchase_amount) / count(distinct customer_id), 2) as revenue_per_customer
from customer
group by location
order by revenue_per_customer desc
limit 10;


-- Q6. What are the top 3 products by revenue within each category?
with item_revenue as (
    select category, item_purchased,
           sum(purchase_amount) as revenue,
           row_number() over (partition by category order by sum(purchase_amount) desc) as item_rank
    from customer
    group by category, item_purchased
)
select item_rank, category, item_purchased, revenue
from item_revenue
where item_rank <= 3
order by category, item_rank;


-- Q7. Does discount usage differ across New, Returning, and Loyal customers?
with customer_type as (
    select customer_id, previous_purchases, discount_applied,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from customer
)
select customer_segment,
       round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*), 2) as pct_using_discount
from customer_type
group by customer_segment
order by pct_using_discount desc;


-- Q8. Do subscribed customers spend more, on average, than non-subscribed customers?
select subscription_status,
       count(*) as num_customers,
       round(avg(purchase_amount), 2) as avg_spend,
       round(sum(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by avg_spend desc;


-- Q9. Among repeat buyers (more than 5 previous purchases), what share are
-- subscribed vs. not subscribed?
select
    subscription_status,
    count(*) as repeat_buyers,
    round(100.0 * count(*) / sum(count(*)) over (), 2) as pct_of_repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. Which customers spent above the average purchase amount but gave a
-- below-average review rating?
select customer_id, purchase_amount, review_rating
from customer
where purchase_amount > (select avg(purchase_amount) from customer)
  and review_rating < (select avg(review_rating) from customer)
order by purchase_amount desc
limit 20;
